### ISSUE TITLE
Issue with marking all as migrated

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#124]
If you try to run `Migrations mark_migrated 123` it will tell you that this is not a valid version.
But if you do `Migrations mark_migrated *` with the wildcard operator it will say

    Migration successfully marked migrated !

But will just add 0 as version in the DB. Doing it again results in

    An error occurred : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'

Now, while I think `*` was never really supported, I think the intuitive thing here would actually to support marking all as migrated.

**Comment by HavokInspiration** [comment]
This is an interesting idea.
About the ``*`` operator, it is indeed not supported. To be honest, the unexpected result from using might be due to some conditions being matched by a ``glob`` or something like that. I look into that.

What about ``mark_migrated all`` instead of the ``*`` ?

**Comment by dereuromark** [comment]
I dont think it warrants an own command as the use case is not that common.

**Comment by HavokInspiration** [comment]
No no I was thinking of adding a special value "all" to the $version argument of the mark_migrated command. If used instead of a date all found migrations will ne migrated.

-----Message d'origine-----
De : "Mark S." <notifications@github.com>
Envoyé : ‎13/‎09/‎2015 11:33
À : "cakephp/migrations" <migrations@noreply.github.com>
Cc : "Yves P." <havokinspiration@gmail.com>
Objet : Re: [migrations] Issue with marking all as migrated (#124)

I dont think it warrants an own command as the use case is not that common.

**Comment by dereuromark** [comment]
I see.
Well, either way works for me. The wildcard on the same command just made sense to me from a UNIX point of view ;)

**Comment by dereuromark** [comment]
Closing as PR is open.
