### ISSUE TITLE
RFC - Pick a version for phinx?

### ISSUE THREAD

**Issue by sitedyno** [cakephp/migrations#144]
cakephp/app will soon ship with composer minimum-stability stable. I just changed a project to use minimum-stability stable because phpunit wants php7 with minimum-stability dev. This causes composer to complain because migrations wants robmorgan/phinx dev-master. I've worked around it for the moment by doing "robmorgan/phinx": "dev-master as 0.4.6"

**Comment by HavokInspiration** [comment]
We currently need ``dev-master`` because there are fixes in phinx that were not part of the last release (0.4.6)
Those fixes are around binary types for MySQL and ON UPDATE / ON DELETE parts of foreign key constraints statements.
Without the latest fix, migrations using SQLite can have their tables dropped in some conditions / use  cases because of SQL queries being wrong.

We've been waiting for a new release on phinx in order to put it back the way it was before but phinx seems to have stopped for the the last two month or so.

**Comment by HavokInspiration** [comment]
This has been done with the release of the 1.5.0 version of the plugin.
