### ISSUE TITLE
Why ignore i18n table in MigrationSnapshotTask?

### ISSUE THREAD

**Issue by adayth** [cakephp/migrations#154]
The i18n table is ignored when doing bake migration_snapshot directly in code, without a direct option to override this (except creating a new plugin/Task and override it of course).

I think is an usual use case, to include i18n table in the "Initial" migration file.

**Comment by HavokInspiration** [comment]
I suspect the reason was because the i18n table can be generated in another way (using the i18n.sql file shipped with the app skeleton).
I agree one should at least be able to opt-out of the behavior (using an option flag for instance). But I would have no problem with removing the thing altogether as I don't think this is really necessary.

**Comment by lorenzo** [comment]
Let's remove it

**Comment by HavokInspiration** [comment]
#156 is up.
