### ISSUE TITLE
Allowing to migrate a specific migration

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/migrations#173]
Issue #171 raised the question about the possibility to migrate only one specific migration.
Currently, the ``target`` option only allow to migrate up to that specific migration but not the specific targetted migration.

Which lead to the question : should we allow users to migrate one specific migration ? An implementation of an option such as ``--only`` (as currently available for the ``mark_migrated`` command) to be used along ``target`` with the should be enough.

**Comment by josegonzalez** [comment]
What is the `-t` flag?

**Comment by dakota** [comment]
I don't think it makes sense to only migrate one migration. That's like
wanting to upgrade from cake 3.1.3 to 3.1.5 without the changes in 3.1.4.
Migrations should be sequential and build on top of each other.

**Comment by dereuromark** [comment]
I also wonder what the use case here would be. Having -t to a specific version should be totally sufficient.

I would rather focus the energy on building a new diff (migration file) from new changes to DB since the last migration ;)

**Comment by HavokInspiration** [comment]
@josegonzalez The ``-t`` option allows you to define a target timestamp. If you use it, it will migrate all migrations from the last one migrated up to the one specified.

@dereuromark I'm clueless about the use case. Maybe we should ask @Penergy who opened the issue in the first place. 

@Penergy What is your use case for wanting to run only one migration ?

**Comment by Penergy** [comment]
I used -migrate create[Model] to create a file. After developing, I tried to modify this file and update the tables. However, I don't want to create update file in migrations during development unless the web app is on public.

**Comment by dereuromark** [comment]
@Penergy IMO the correct approach is to

- first run migrate to be up to date with the status quo
- then make your new migration file and modify it
- run it and then commit this new file

There should never be the need for your use case as this is not an approach you should ever do from what I can understand from your scenario.

**Comment by HavokInspiration** [comment]
I understand your concern : you don't want to have, while in development, multiple files interacting with the same table until it is not deployed to keep a clean migrations archive.

In case you really want to do that, you should rollback the migration, edit your migration files and then rerun the migration.
Without doing so and even if there was such a feature (migrating only one migration file), you will get errors when running the migrations since there will be instructions that were already done (table already exists for instance).

Since the general tendency is against the feature, it will probably not be implemented.
I'll leave this open a bit more in case users want to give their opinion on this.

**Comment by dereuromark** [comment]
We can always reopen if someone makes a valid point or use case.

**Comment by renepupil** [comment]
> We can always reopen if someone makes a valid point or use case.

1. You develop a new feature with a migration file. 
2. Before the feature is finished new migrations have gone to master.
3. Rebasing master results in migration files NEWER then the one added with the feature.
4. You execute master migrations because they are mandatory for the application.
5. Master migration are irreversible.
6. You want to rollback and change the migration file of the feature.

Now instead of justing rolling back the ONE migration file, i have to manually perform all rollback operations...

Allowing to rollback a specific version would make development a hell of a lot easier...

**Comment by dereuromark** [comment]
Should we not implement this directly in phinx then? https://github.com/cakephp/phinx
I recommend making a PR there, get it merged and released

This here is just a wrapper in the end, so if this is not "cake" specific IMO, it would get included by design if done in the original repo, which in this case applies.
