### ISSUE TITLE
Running *all* migrations, including those for loaded plugins

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/migrations#176]
When running smaller applications on a PaaS system, it's useful to run migrations on deploy. I currently need to manually execute migrations for the main application and then separately run them for plugins like so:

``` shell
bin/cake migrations migrate
bin/cake migrations migrate -p Blog
```

If it's not already possible, it would be nice to be able to run _all_ migrations at once, like so:

``` shell
bin/cake migrations migrate --all
```

Thoughts?

**Comment by lorenzo** [comment]
I usually make a script myself, since it is more often than not that the order in which the plugins are loaded is important

**Comment by HavokInspiration** [comment]
This feature was asked once before : https://github.com/cakephp/migrations/issues/115

I share the same concern as @lorenzo regarding plugins priority.
Currently, we could do it by looping on a ``Plugin::loaded()`` result, but what if you need to load a ``Users`` plugin before a ``Comments`` plugin ? Since the list of loaded plugin is returned sorted, there could be troublesome, unless we implements an interactive shell, but that would kill the point.

Maybe through a config file or a ``Configure`` parameter registration to set up the list of plugins ? And if not present, run them in the alphabetical order.

**Comment by dereuromark** [comment]
If priority is an issue (in many cases it is not) you shouldn't use such a command.
But for those where this suffices a --all one seems to be a good idea.

An optional Configure param on top might also be useful then, I guess.

**Comment by dereuromark** [comment]
Should we close this as order matters, and we usually advise to use specific commands here as list in the deployment scripts?
