### ISSUE TITLE
Baking snapshot from mysql changes longtext to text

### ISSUE THREAD

**Issue by half2me** [cakephp/migrations#211]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 3.2.5
* Migrations plugin version: 1.5.7
* Bake plugin version (if relevant): 1.2.3
* Database server MySQL 5.7.10
* PHP Version: 5.6.18
* Platform / OS: OSX 10.11

### What you did
I baked a snapshot of my database. I have a field called `data` with `LONGTEXT` type
`bin/cake bake migration_snapshot longtextdata --plugin Queue`

### Expected Behavior
I would expect the output to have type TEXT, with the limit option set.

### Actual Behavior
I get the following (limit is null):
```php
->addColumn('data', 'text', [
                'default' => null,
                'limit' => null,
                'null' => true,
            ])
```

When I use migrations to setup a new database, `LONGTEXT` type is not set, but `TEXT` is used instead. This way when I want to save long text data, the end gets cut off.

The `limit` should be set like this: https://stackoverflow.com/questions/4443477/rails-3-migration-with-longtext

**Comment by HavokInspiration** [comment]
The problem comes from the CakePHP schema reflection tool.
I built a table with a ``LONGTEXT`` column and the schema reflection returns :

```php
object(Cake\Database\Schema\Table) {
	[protected] _table => 'books'
	[protected] _columns => [
		'id' => [
			'type' => 'integer',
			'length' => (int) 11,
			'unsigned' => false,
			'null' => false,
			'default' => null,
			'comment' => '',
			'autoIncrement' => true,
			'baseType' => null,
			'precision' => null
		],
		'title' => [
			'type' => 'string',
			'length' => (int) 255,
			'null' => false,
			'default' => null,
			'comment' => '',
			'baseType' => null,
			'precision' => null,
			'fixed' => null
		],
		'description' => [
			'type' => 'text',
			'length' => null,
			'null' => false,
			'default' => null,
			'comment' => '',
			'baseType' => null,
			'precision' => null
		]
	]
    // ...
}
```

There's nothing that can currently be done on the migrations plugin side.
I'll open a ticket in the core repo to discuss this.

I will put on hold for the moment, pending what will be decided in the ticket.

**Comment by HavokInspiration** [comment]
Please note that right now you can "fix" the generated migration file by specifying the length this way :

```php
use Phinx\Db\Adapter\MysqlAdapter;

//...

->addColumn(
    'data',
    'text',
    [
        'limit' => MysqlAdapter::TEXT_LONG
    ]
)

```

**Comment by thinkingmedia** [comment]
@HavokInspiration I don't think this is a fix. This is actually the **correct** way to do it.

**Comment by half2me** [comment]
@thinkingmedia that would change the migration to be MySQL specific. A longer TEXT field type should be for all supported databases.

**Comment by HavokInspiration** [comment]
@thinkingmedia I didn't say it was not. The "fix" word was only applied in the context of the migration generated by bake being wrong because right now, CakePHP schema system always returns a ``text`` type whether it is ``tiny``, ``medium`` or ``long``. So it's impossible for the baking task to know which length to apply.

@half2me Eventually, the migration file will look like it is MySQL specific but there might be a way to "convert" it based on what type of vendor you are migrating to. This is going to need some thinking and work to do so though.

**Comment by half2me** [comment]
@HavokInspiration When you specify a 'limit' value to the TEXT field, phynx will automatically select the correct type to use: TEXT, LONGTEXT etc. So what I would suggest is when making a snapshot of the database, if the type is TEXT, don't use a 'limit' field. If the type is LONGTEXT or something with a larger or smaller limit, then the limit field be added to the migration file.

Basically if I have a database and I generate a snapshot, I expect to get the exact same database back, when running the migration somewhere else. This is currently not the case. I also suggest that we use a database agnostic approach, such as using the 'limit' field. No MySQL :)

**Comment by thinkingmedia** [comment]
@HavokInspiration sorry, I missed that. I have not looked at the code for generating migrations.

**Comment by HavokInspiration** [comment]
I tested again since 3.2.7 was released including the necessary improvements in the Schema management classes and it now properly works (see https://github.com/cakephp/cakephp/pull/8543 and https://github.com/cakephp/cakephp/pull/8605)

The thing to know is that it will use a type ``text`` whatever the length is and will use a constant value from the ``Schema\Table`` class matching the length. These values are the same as phinx so it will not lose its marbles when migrating : it will create the proper column type (whether long, medium or tiny).
