### ISSUE TITLE
cake migrations dump should mention details

### ISSUE THREAD

**Issue by dereuromark** [cakephp/migrations#244]
The

    cake migrations dump

should mention how it creates that dump.
Like from previous migration files or directly from the current DB schema.

Currently the problem seems to be that a freshly generated dump file will result in a lot of (wrong because unchanged) tables for the next "diff" baked with `cake bake migration_diff ...`.

Mysql and Cake3.2

**Comment by HavokInspiration** [comment]
This issue is potentially linked to #232, but I'm not really sure. I didn't get a chance to look into it to see what is going on.

But out of curiosity, can you explain in details what you are doing (schema db, commands, etc.) and what you get ?
This will give me another scenario to test and allow me to see if this is linked to #232 or not.

**Comment by dereuromark** [comment]
Windows and latest stable bundle version.
Removing the .lock file from Migrations folder and running the dump command.
Then running the bake migration_diff - which should have been outputting a "no changes" file IMO.

**Comment by HavokInspiration** [comment]
I could reproduce and opened #248 to fix what you are experiencing @dereuromark 

I can a note in the docs about what the dump command does.
FYI, it will now (after #248 is merged) add every schemas from the tables it finds in your connection and add them to the dump file.
