### ISSUE TITLE
Not picking up aliases defined in bootstrap.php

### ISSUE THREAD

**Issue by ricardograca** [cakephp/migrations#324]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10.
* Migrations plugin version: Can't find that info anywhere. Probably whatever comes with CakePHP 3.2.10.
* Bake plugin version (if relevant): Same as above.
* Database server (MySQL, SQLite, Postgres): Postgresql 9.5.8
* PHP Version: 7.0.22-0ubuntu0.16.04.1
* Platform / OS: Ubuntu 16.04.2

### What you did
This is a new project and I'm trying to just run a migration. However I don't have a `default` connection. I opted for more descriptive names, so I have a `development` connection that is aliased as `default` when the `PHP_ENV` variable is set to `development`, and the same thing for `production` and `staging`. This seems to work fine when running `cake server`, but not when running `bin/cake migrations migrate`.

For whatever reason it always tries to alias a `default` connection and it fails, even though my `config/bootstrap.php` file has this part:

```php
if (!getenv('PHP_ENV')) {
	putenv('PHP_ENV=development');
}

switch(getenv('PHP_ENV')) {
	case 'development':
		ConnectionManager::alias('development', 'default');
		break;
	case 'staging':
		ConnectionManager::alias('staging', 'default');
		break;
	case 'production':
		ConnectionManager::alias('production', 'default');
		break;
}
```
Note that the migrations plugin is only loaded after the above code.

### Expected Behavior
I should be able to run `bin/cake migrations migrate` without having to manually specify a connection name on the command line since `default` should be aliased to the `development` connection specified in `config/database.php`.

This is merely a convenience and to maintain some consistency with what happens when running `cake server`, where the connection name to use is derived from the `PHP_ENV` environment variable.

### Actual Behavior
When running `bin/cake migrations migrate`:
```
Exception: Cannot create alias of "default" as it does not exist. in [/home/ricardo/src/my_project/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php, line 155]
```

This is somewhat related with #69, but goes one step further since the `--connection` parameter shouldn't even be necessary in this case because the `default` connection should be an alias, but apparently this plugin doesn't like that.

**Comment by AD7six** [comment]
> so I have a development connection that is aliased as default when the PHP_ENV variable is set to development,

May I ask why you are doing that - why is it necessary for a single install to have any awareness at all of other environments?

**Comment by ricardograca** [comment]
Sure. The idea is to have different databases according to the environment. If I need to test different environments on the same machine, I can just use different databases for each which should prevent data loss and misleading results.

In any case I'm not even sure this would be possible with the current way the `ConfigurationTrait.php` file handles connections, but I'm just putting it out there. Maybe don't try to alias anything if the user hasn't specified the `--connection` parameter?

**Comment by AD7six** [comment]
You are likely to (eventually) conclude that idea is not a good one @ricardograca :). Hopefully before the "I just dropped the production db by mistake" or equivalent error which everyone inevitably, makes. It's a subtle difference but I recommend to change your workflow so that the code is only aware of one environment; "the" environment. If you need to connect to a different environment _change the config_. A reference: https://12factor.net/config

Regarding the ticket itself, the problem is that the connection manager [won't allow aliasing an alias](https://github.com/cakephp/cakephp/blob/master/src/Datasource/ConnectionManager.php#L154) - I don't know if that is really a problem.. it's a bit of an edge case. 

Not sure if it's a fair assumption that the default connection will always exist, which is what the code is currently expecting, however since this plugin is currently [trying to alias the default connection to default](https://github.com/cakephp/migrations/blob/master/src/Command/CommandTrait.php#L67) when no args are passed - seems probably find to just wrap that in a conditional statement (if $name is not 'default'). Would you like to create a PR for that?

**Comment by ricardograca** [comment]
> You are likely to (eventually) conclude that idea is not a good one @ricardograca :)

It's how Rails works, which is what I thought CakePHP was based on, so my expectation was that migrations would work in a similar way to the Rails way, i.e. it picks up the environment from the `RAILS_ENV` variable and uses the correct database config according to that.

> If you need to connect to a different environment: change the config

That would get tedious really fast, when I could just change the current environment name. With your proposal I would have to look up the username, password, database name and possibly port and host whenever I want to use the database from another environment.

>  Not sure if it's a fair assumption that the default connection will always exist

In my opinion it isn't, but it seems that is common throughout CakePHP in general, so probably it's on purpose. It would be better if it was a bit more flexible.

> Would you like to create a PR for that?

That would solve my problem right?

**Comment by dereuromark** [comment]
@ricardograca ping

**Comment by ricardograca** [comment]
Yes @dereuromark?

**Comment by dereuromark** [comment]
Are you still interested in creating that PR?

**Comment by ricardograca** [comment]
Ah right. No, I've moved on since then. I'll close this issue.
