### ISSUE TITLE
Must use create or update when using change() 

### ISSUE THREAD

**Issue by pjosephson** [cakephp/migrations#43]
The current template (migration.ctp) is using a save() call. Which makes reversing not possible.  Phinx documentation states:

When creating or updating tables inside a change() method you must use the Table create() and update() methods. Phinx cannot automatically determine whether a save() call is creating a new table or modifying an existing one.

**Comment by HavokInspiration** [comment]
I don't know if this issue is (still) valid.
When generating migrations files with ``bake``, the method to use is dynamically generated with the ``MigrationHelper::tableMethod()``, whether it is a snapshot or a "regular" migration :

- https://github.com/cakephp/migrations/blob/master/src/Template/Bake/config/snapshot.ctp#L17
- https://github.com/cakephp/migrations/blob/master/src/Template/Bake/config/skeleton.ctp#L17

I tested generating various migrations (from the README) and ``create`` or ``update`` are used in all cases.

**Comment by markstory** [comment]
Closing then :smile:
