### ISSUE TITLE
The datasource configuration "default" was not found. 

### ISSUE THREAD

**Issue by mbryja** [cakephp/migrations#69]
I'm building multisite application with cakephp 3. I won't use default connection because each of the site will connect to it's own version of database. The database structure will be identical for each site. I want to use cakephp migration to automate create and alter processes. 

I've created my own shell which executes 'bin/cake migrations migrate -c connection_name' command on each connection it finds. 

Unfortunately, I receive the following error:
[Cake\Datasource\Exception\MissingDatasourceConfigException]  
  The datasource configuration "default" was not found.

It is caused by  'bootstrap' method in 'src/Configuration trait' at line 169.

Here is how I've solved it: 
```
 public function bootstrap(InputInterface $input, OutputInterface $output)
    {
        parent::bootstrap($input, $output);

        $connectionStr = 'default';
        if ($this->input->getOption('connection')) {
            $connectionStr = $this->input->getOption('connection');
        }

        $connection = $this->getManager()->getEnvironment('default')->getAdapter()->getConnection();
        ConnectionManager::get($connectionStr)->driver()->connection($connection);
    }
```
I'm not sure if this is preferable solution.

**Comment by lorenzo** [comment]
You need to use the `--connection` option to change the connection you want to use if not default

**Comment by mbryja** [comment]
Current bootstrap always use default:

    public function bootstrap(InputInterface $input, OutputInterface $output)
    {
        parent::bootstrap($input, $output);
        $connection = $this->getManager()->getEnvironment('default')->getAdapter()->getConnection();
        ConnectionManager::get('default')->driver()->connection($connection);
    }

**Comment by lorenzo** [comment]
And that is what we want... If you want something that is not `default` then you need to use `--connection other_connection`

**Comment by mbryja** [comment]
I execute the following command 'bin/cake migrations migrate -c connection_name'. In my app I don't use default at all for security reason so above code will not work.

**Comment by lorenzo** [comment]
So, when you execute `bin/cake migrations migrate -c connection_name` you get the exception?

**Comment by mbryja** [comment]
yes

**Comment by mbryja** [comment]
and as I've mentioned the error is thrown in src/ConfigurationTrait at line 173

**Comment by lorenzo** [comment]
Thanks, sorry for the misunderstanding

**Comment by mbryja** [comment]
looks good, thank you

**Comment by Avemaar** [comment]
Yesterday when i tried to upload to server enviroment i got this error too.
My projects works fine in localhost but after uploading to server.Checking the pages was okey,
the problem occurred after triing to inlog.
The infos i can get is the toggle vendor stack frames:
`
⟩ Cake\ORM\Table->addBehavior APP/Model/Table/UsersTable.php, line 40:
 $this->addBehavior('Acl.Acl', ['type' => 'requester']);


⟩ Cake\Controller\Controller->loadModel APP/Controller/AppController.php, line 518

public function setMenu($id=null)
--
  | {
  | $this->loadModel('Users');
  | $userRoles=$this->Users->find('all',[


⟩ App\Controller\AppController->setMenu APP/Controller/AppController.php, line 501:
 $this->setMenu($this->Auth->User('id'));
`
I spent hours to figure out what the problem is but since it was okey in localhost i dont know.
Interestingly if i reboot the server's php version from 5.6->7 or 7->5.6 its begans to work again
until i try to inlog.Something went wrong during i write this post.No i can not reboot to work normal again its stay in the "The datasource configuration "default" was not found." state
