### ISSUE TITLE
Mulitple Simultaneous Database Connections are Not Supported?

### ISSUE THREAD

**Issue by hypnoboutique** [cakephp/migrations#81]
I am working on an existing CakePHP 3.0 application which necessarily uses multiple databases. 

We have had some problematic rollouts and I want to introduce migrations to improve our recovery speed with db rollbacks, so I need to write migrations that implicitly target the correct datasource connection. 

The option seems to have been considered with 'bake migrate [...] -c' but the resulting migration file contains no reference to the datasource.

You can specify a connection in the Migrations shell with the -c option too, which does target the correct datasource, but having to supply a target per migration and move one migration at a time defeats the object, somewhat...

I could keep db specific migrations separate directories and run migrate on those files/connection, but this still makes rolling back to a specific point in time quite cumbersome.

Is this a bug/issue, as it seems, or am I missing something?

**Comment by lorenzo** [comment]
That s tool was not thought for maintaining different connections with different schemas. If you want different schemas for different connections  I would suggest having different directories for each one.

In mi view, rolling back to a police my in time is usually more a development task than something that you would do on a live system, so I think the extra work is not mucho of a tragedy. A way to speed it up is to create migrations that when ran, will do the rolling back operations.

That way you only need to stay on the latest migration instead of picking the right version to use
